version: '3'
services:
  store-locator-backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 10100:10100

  postgres:
    image: postgis/postgis:13-master
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres

  flyway:
    image: flyway/flyway
    command: -url=jdbc:${POSTGRES_URL} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
