version: '3'
services:
  store-locator-backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 10100:10100

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5433:5432
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
